name: build
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  LIBVNC_VERSION: "0.9.13"

jobs:
  native-windows:
    strategy:
      matrix:
        include:
        - arch: Win32
          rid: win7-x86
          triplet: x86-windows
        - arch: x64
          rid: win7-x64
          triplet: x64-windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          path: src
      - name: Clone LibVNCServer
        run: |
          git clone --branch LibVNCServer-${{ env.LIBVNC_VERSION }} --depth 1 https://github.com/LibVNC/libvncserver/
          git show
      - name: Cache vcpkg downloads
        uses: actions/cache@v4
        with:
          path: C:/vcpkg/downloads
          key: vcpkg_downloads | ${{ matrix.triplet }}
      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: C:/vcpkg/installed
          key: vcpkg_downloads | ${{ matrix.triplet }}
      - name: Install dependencies
        run: |
          C:\vcpkg\vcpkg.exe version
          C:\vcpkg\vcpkg.exe install libpng:${{ matrix.triplet }}
          C:\vcpkg\vcpkg.exe install zlib:${{ matrix.triplet }}
          C:\vcpkg\vcpkg.exe install libjpeg-turbo:${{ matrix.triplet }}
      - name: Configure LibVNC
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=ON -DWITH_OPENSSL=OFF -DWITH_GCRYPT=OFF -DWITH_GNUTLS=OFF -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/${{ matrix.rid }} ../libvncserver/ -A ${{ matrix.arch }}
      - name: Compile LibVNC
        run: |
          cmake --build . --target vncserver --config Release
          dir .
        working-directory: build
      - name: Install LibVNC
        run: |
          New-Item ${{ github.workspace }}\libvnc\${{ matrix.rid }}\ -ItemType Directory -Force
          copy Release\*.* ${{ github.workspace }}\libvnc\${{ matrix.rid }}\
        working-directory: build
      - name: Build vnclogger
        run : |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg/scripts/buildsystems/vcpkg.cmake -A ${{ matrix.arch }} ..
          cmake --build . --config Release
          New-Item ${{ github.workspace }}\libvnc\${{ matrix.rid }} -ItemType Directory -Force
          copy Release\*.* ${{ github.workspace }}\libvnc\${{ matrix.rid }}
        working-directory: '${{ github.workspace }}/RemoteViewing.LibVnc.Logging'
      - name: Upload libvnc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvnc-${{ github.run_id }}-${{ matrix.rid }}
          path: |
            ${{ github.workspace }}\libvnc\
